import React, { useEffect, useState } from 'react';
import Title from '../components/ui/Title';
import commuteArts from '../assets/vector/commute-helper-1.svg';
import missionArts from '../assets/vector/mission.svg';
import visionArts from '../assets/vector/vision.svg';

const aboutNavLinks = [
  {
    id: 'about-us',
    title: 'About',
    description:
      'We are committed to transforming daily commutes into sustainable and efficient journeys. Our platform bridges the gap between riders and passengers, enabling them to share rides, reduce travel expenses, and contribute to a greener planet. By connecting people traveling the same route, we ensure that every empty seat serves a purpose. We empower our users to make a positive impact on the environment, one shared ride at a time. Join us in our mission to create a more sustainable future for all. Together, we can make a difference.',
    image: commuteArts,
  },
  {
    id: 'our-mission',
    title: 'Our Mission',
    description:
      'Our mission is to reduce the number of empty car seats on the road by connecting drivers with passengers traveling the same route. We aim to create a more sustainable and efficient transportation system that benefits both the environment and the community. By encouraging ride-sharing, we help reduce traffic congestion, lower carbon emissions, and save money on fuel costs. Our platform is designed to make carpooling convenient, safe, and affordable for everyone. We believe that by working together, we can build a better future for all.',
    image: missionArts,
  },
  {
    id: 'our-vision',
    title: 'Our Vision',
    description:
      'Our vision is to revolutionize the way people commute by making carpooling the preferred mode of transportation. We envision a world where every car seat is filled with passengers who share the same destination. By promoting ride-sharing, we aim to create a more sustainable and inclusive society that benefits everyone. We believe that by leveraging technology and innovation, we can transform the way people travel and reduce their carbon footprint. Our goal is to build a global community of like-minded individuals who are committed to making a positive impact on the environment. Join us in our journey to create a greener and more connected world.',
    image: visionArts,
  },
];

const AboutPage: React.FC = () => {
  const [activeSection, setActiveSection] = useState<string | null>(null);

  useEffect(() => {
    const handleScroll = () => {
      const sections = aboutNavLinks.map((navLink) =>
        document.getElementById(navLink.id)
      );
      const currentSection = sections.find(
        (section) =>
          section &&
          section.offsetTop <= window.scrollY &&
          section.offsetTop + section.offsetHeight > window.scrollY
      );
      setActiveSection(currentSection ? currentSection.id : null);
    };

    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <>
      <main>
        <Title title="Every year, over 1.3 billion tons of CO₂ emissions are generated by vehicles worldwide, with nearly 70% of car seats remaining empty during daily commutes." />
        <div className="mt-24" />
        <div className="grid grid-cols-4">
          <div className="sticky top-0 pt-16 col-span-1 max-h-fit">
            <ul className="space-y-8">
              {aboutNavLinks.map((navLink) => (
                <li key={navLink.id}>
                  <a
                    href={`#${navLink.id}`}
                    className={`text-2xl transition-300 ${
                      activeSection === navLink.id
                        ? 'font-bold text-teal-400'
                        : 'font-normal'
                    }`}
                  >
                    {navLink.title}
                  </a>
                </li>
              ))}
            </ul>
          </div>
          <aside className="col-span-3 space-y-12">
            {aboutNavLinks.map((navLink) => (
              <section
                key={navLink.id}
                id={navLink.id}
                className="pt-14"
              >
                <p className="text-xl">{navLink.description}</p>
                <img src={navLink.image} alt={navLink.title} />
              </section>
            ))}
          </aside>
        </div>
      </main>
    </>
  );
};

export default AboutPage;